### PR TITLE
dateUpload for AniWorld & SerienStream

### PR DESCRIPTION
**Pull request by NBA2K1**

### CODE REVIEW

**Comment by kodjodevf** [comment]
Use this code instead :

   ```
 async getUploadDateFromEpisode(url) {
        const baseUrl = this.source.baseUrl;
        const res = await this.client.get(baseUrl + url);
        const document = new Document(res.body);
        const dateString = document.selectFirst('strong[style="color: white;"]').text;
        const dateTimePart = dateString.split(", ")[1];
        const [date, time] = dateTimePart.split(" ");
        const [day, month, year] = date.split(".");
        const formattedDate = `${year}-${month}-${day.padStart(2, "0")}`;
        return String(new Date(formattedDate).valueOf());
    }
```

**Comment by NBA2K1** [comment]
> Use this code instead :
> 
> ```
> async getUploadDateFromEpisode(url) {
>      const baseUrl = this.source.baseUrl;
>      const res = await this.client.get(baseUrl + url);
>      const document = new Document(res.body);
>      const dateString = document.selectFirst('strong[style="color: white;"]').text;
>      const dateTimePart = dateString.split(", ")[1];
>      const [date, time] = dateTimePart.split(" ");
>      const [day, month, year] = date.split(".");
>      const formattedDate = `${year}-${month}-${day.padStart(2, "0")}`;
>      return String(new Date(formattedDate).valueOf());
>  }
> ```

But your code doesn't make use of the time, and doesn't take the Daylight Saving Times into account. That's why I wanted to use Intl, and since it isn't implemented I made my own small function getLastSundayOfMonth to determine whether the time was in MESZ (CEST) or MEZ (CET). 
BTW the dateString would look like this: "Sonntag, 08.09.2024 16:40", so there is no need to use padStart.

**Comment by kodjodevf** [comment]
It's because it doesn't seem to return the right values

**Comment by NBA2K1** [comment]
I tried it on https://aniworld.to/anime/stream/attack-on-titan
and on
https://aniworld.to/anime/stream/dan-da-dan and got the correct values. 
Where did you get wrong values?

**Comment by NBA2K1** [comment]
Huh strange, I've only tested it in the code-editor and it worked there perfectly:

grafik

Now I tried it on the normal anime view and it doesn't work, like you said:

grafik

How come?

**Comment by kodjodevf** [comment]
Fixed, use it like this:

    ```
async getUploadDateFromEpisode(url) {
        const baseUrl = this.source.baseUrl;
        const res = await this.client.get(baseUrl + url);
        const getLastSundayOfMonth = (year, month) => {
            const lastDay = new Date(year, month, 0);
            const lastSunday = lastDay.getDate() - lastDay.getDay();
            return new Date(year, month - 1, lastSunday);
        };
        const document = new Document(res.body);
        const dateString = document.selectFirst('strong[style="color: white;"]').text;
        const dateTimePart = dateString.split(", ")[1];
        const [date, time] = dateTimePart.split(" ");
        const [day, month, year] = date.split(".");
        const [hours, minutes] = time.split(":");
        const dayInt = parseInt(day);
        const monthInt = parseInt(month);
        const yearInt = parseInt(year);
        const hoursInt = parseInt(hours);
        const minutesInt = parseInt(minutes);
        const lastSundayOfMarch = getLastSundayOfMonth(yearInt, 3);
        const lastSundayOfOctober = getLastSundayOfMonth(yearInt, 10);
        const jsDate = new Date(yearInt, monthInt - 1, dayInt, hoursInt, minutesInt);
        // If Date between lastSundayOfMarch & lastSundayOfOctober -> CEST (MESZ)
        const isInDST = jsDate >= lastSundayOfMarch && jsDate < lastSundayOfOctober;
        let timeZoneOffset = isInDST ? 0 : 1;
        // If it's in CEST, subtract 1 hour from UTC (to get local time in CEST)
        const correctedTime = new Date(jsDate.getTime() + (timeZoneOffset - 1) * 60 * 60 * 1000);
        return String(correctedTime.valueOf());
    }
```

**Comment by NBA2K1** [comment]
Oh I feel dumb. I literally put it into my comment, that it's in milliseconds. But I converted it into seconds, since the Unix timestamp uses seconds. I have only paid attention to the "dateUpload is a string" part of the comment, hahaha.

**Comment by kodjodevf** [comment]
Also don't forget to increment version number

**Comment by kodjodevf** [comment]
Thanks

**Pull request merged**
